export REG_TEST_HOME=/c/UQAM-DEV
export REG_TEST_GIT=$REG_TEST_HOME/GIT
export JAVA_HOME=$REG_TEST_HOME/jdk
export SOLR=$REG_TEST_HOME/solr-7.7.2
export TOMCAT=$REG_TEST_HOME/apache-tomcat-8.5.11
export VIVO_HOME=$REG_TEST_HOME/vivo
export VIVO_HOME_ORIG=$REG_TEST_HOME/vivo_orig